"""empty message

Revision ID: 71da8e5f9314
Revises: 3237ba0d84f4
Create Date: 2023-12-10 21:57:03.268241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71da8e5f9314'
down_revision = '3237ba0d84f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_bids_listing_id_listings')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_bids_users_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    # ### end Alembic commands ###
